In [1]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt
import sklearn
from sklearn.datasets import load_boston

In [2]:
boston = load_boston()
df=pd.DataFrame(boston.data, columns=boston.feature_names)
df['PRICE']=boston.target
df.head()

/opt/conda/lib/python3.10/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np

        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.
    :func:`~sklearn.datasets.fetch_california_housing`) and the Ames housing
    dataset. You can load the datasets as follows::

        from sklearn.datasets import fetch_california_housing
        housing = fetch_california_housing()

    for the California housing dataset and::

        from sklearn.datasets import fetch_openml
        housing = fetch_openml(name="house_prices", as_frame=True)

    for the Ames housing dataset.
  warnings.warn(msg, category=FutureWarning)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,PRICE
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2

In [4]:
#independent and dependent feature
X=df.drop('PRICE',axis=1)
Y=df[['PRICE']]

In [5]:
X

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88

In [6]:
Y

     PRICE
0     24.0
1     21.6
2     34.7
3     33.4
4     36.2
..     ...
501   22.4
502   20.6
503   23.9
504   22.0
505   11.9

[506 rows x 1 columns]

In [7]:
from sklearn.impute import SimpleImputer ## HAndling Missing Values
from sklearn.preprocessing import StandardScaler # HAndling Feature Scaling
## pipelines
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [9]:
numerical_cols = X.select_dtypes(exclude='object').columns

In [10]:
## Numerical Pipeline
num_pipeline=Pipeline(
    steps=[
    ('imputer',SimpleImputer(strategy='median')),
    ('scaler',StandardScaler())

    ])

In [12]:
preprocessor=ColumnTransformer([
('num_pipeline',num_pipeline,numerical_cols)])

In [13]:
preprocessor=ColumnTransformer([
('num_pipeline',num_pipeline,numerical_cols)])

In [14]:
## Train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.30,random_state=30)

In [15]:
X_train=pd.DataFrame(preprocessor.fit_transform(X_train),columns=preprocessor.get_feature_names_out())
X_test=pd.DataFrame(preprocessor.transform(X_test),columns=preprocessor.get_feature_names_out())

In [16]:
X_train.head()

,num_pipeline__CRIM,num_pipeline__ZN,num_pipeline__INDUS,num_pipeline__CHAS,num_pipeline__NOX,num_pipeline__RM,num_pipeline__AGE,num_pipeline__DIS,num_pipeline__RAD,num_pipeline__TAX,num_pipeline__PTRATIO,num_pipeline__B,num_pipeline__LSTAT
0,-0.366746,-0.500976,1.633937,-0.263603,0.620184,-0.499013,0.903518,-0.883813,-0.627436,0.195035,1.265311,0.223312,0.645803
1,0.286850,-0.500976,1.072399,-0.263603,1.397653,0.017095,0.530742,-0.517935,1.677829,1.556856,0.807596,0.428446,0.231314
2,2.159897,-0.500976,1.072399,-0.263603,1.222941,-1.315152,0.992274,-1.009712,1.677829,1.556856,0.807596,0.428446,1.054595
3,1.090223,-0.500976,1.072399,-0.263603,0.384322,0.753409,1.134284,-1.122836,1.677829,1.556856,0.807596,-1.964302,1.056020
4,-0.369270,-0.500976,-0.690741,-0.263603,-0.428089,1.901233,-1.812421,-0.212505,-0.166383,-0.578050,-0.474007,0.215173,-1.203019

In [17]:
## Model Training
from sklearn.linear_model import LinearRegression,Lasso,Ridge,ElasticNet
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [18]:
regression=LinearRegression()
regression.fit(X_train,y_train)

LinearRegression()

In [19]:
regression.coef_

array([[-1.10616446,  1.0140359 , -0.1031787 ,  0.87291462, -1.84907876,
         3.03013364, -0.24548803, -3.12828083,  3.15131315, -2.65484875,
        -2.03912493,  0.52453944, -3.4247436 ]])

In [20]:
regression.intercept_

array([22.73700565])

In [21]:
import numpy as np
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_square = r2_score(true, predicted)
    return mae, rmse, r2_square

In [22]:
## Train multiple models

models={
    'LinearRegression':LinearRegression(),
    'Lasso':Lasso(),
    'Ridge':Ridge(),
    'Elasticnet':ElasticNet()
}

model_list=[]
r2_list=[]

for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)

    #Make Predictions
    y_pred=model.predict(X_test)

    mae, rmse, r2_square=evaluate_model(y_test,y_pred)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print('Model Training Performance')
    print("RMSE:",rmse)
    print("MAE:",mae)
    print("R2 score",r2_square*100)

    r2_list.append(r2_square)
    
    print('='*35)
    print('\n')

LinearRegression
Model Training Performance
RMSE: 4.679767539468054
MAE: 3.382328457043978
R2 score 70.51993010219368
===================================


Lasso
Model Training Performance
RMSE: 5.052055208771986
MAE: 3.4695898376811676
R2 score 65.64292971779035
===================================


Ridge
Model Training Performance
RMSE: 4.674701556520049
MAE: 3.3716703767354135
R2 score 70.5837216024052
===================================


Elasticnet
Model Training Performance
RMSE: 5.187460830640639
MAE: 3.53328159437827
R2 score 63.77656689772407
===================================

In [23]:
model_list

['LinearRegression', 'Lasso', 'Ridge', 'Elasticnet']